### ISSUE TITLE
[EXPIRED] Compressing multiple files

### ISSUE THREAD

**Issue by sergeevabc** [wg/arc#2]
Dear Will,
Is there a way to compress a few folders or, at least, all files within selected folder?

```
C:\arc.exe --password --create --file temp.arc *.*
password:
GetFileAttributesEx *.*: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by wg** [comment]
Hey @sergeevabc, arc expects the shell to do the glob expansion and pass actual file names to the program. The windows CMD shell doesn't do that, but perhaps there's a way with PowerShell? Afraid I don't actually use Windows so I'm not sure what options exist.
